baseURL = "/"
languageCode = "en-us"
title = "Kalixo Labs LLC"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Kalixo Labs LLC is a consulting firm specializing in computational studies and product optimization."
    meta_og_title = "Kalixo Labs LLC"
    meta_og_type = "website"
    meta_og_url = "https://kalixolabs.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Kalixo Labs LLC is a consulting firm specializing in computational studies and product optimization."


[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


# [[menu.main]]
#     name = "History"
#     url = "/history/"
#     weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
